// src/aws-exports.js (generated by the Amplify CLI)
const awsmobile = {
  aws_project_region: 'YOUR_AWS_REGION',
  aws_cognito_identity_pool_id: 'YOUR_COGNITO_IDENTITY_POOL_ID',
  aws_cognito_region: 'YOUR_AWS_REGION',
  aws_user_pools_id: 'YOUR_USER_POOLS_ID',
  aws_user_pools_web_client_id: 'YOUR_USER_POOLS_WEB_CLIENT_ID',
  oauth: {},
  aws_appsync_graphqlEndpoint: 'YOUR_APPSYNC_GRAPHQL_ENDPOINT',
  aws_appsync_region: 'YOUR_AWS_REGION',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
  aws_user_files_s3_bucket: 'YOUR_S3_BUCKET_NAME',
  aws_user_files_s3_bucket_region: 'YOUR_AWS_REGION'
}

export default awsmobile
